### ISSUE TITLE
Following the instructions for the exercise in workshop-html-css/body/001-hello-world.md results in a failed result

### ISSUE THREAD

**Issue by R-V-S** [Bloc/workshop-html-css#13]
The exercise is missing a step that tells the user to save the changes to the file made in the previous steps, so if you follow the instructions exactly, the "Run" button evaluates an empty file and fails. Missing step in bold below:

...
4. Surround Hello World text with opening and closing paragraph tags.
5. **Click the Save button to save your changes.**
6. Click the Run button.
...

**Comment by getaaron** [comment]
Thanks, @R-V-S
