### ISSUE TITLE
In workshop-html-css/body/013-external-css.md, The exercise instructs the user to open a file and then create another file, which closes the file they just opened

### ISSUE THREAD

**Issue by R-V-S** [Bloc/workshop-html-css#16]
In workshop-html-css/body/013-external-css.md, the exercise says "Open index.html." (though, oddly, this is not a step). Then step 1 is "Create a file named, main.css."... which closes index.html and auto-opens main.css. Suggested steps:

1. Create a file named `main.css`.
2. In `index.html`, copy everything between (but not including) the tags and paste it all into `main.css`</li> <li>Go back to index.html and replace the `<style>` tags (and everything inside them) with a single link tag that connects your HTML file to your CSS file (`href="main.css"`).

**Comment by mikesjewett** [comment]
Thanks @R-V-S 👍
