### ISSUE TITLE
Add an instruction to link to profile.html from index.html

### ISSUE THREAD

**Issue by mikesjewett** [Bloc/workshop-html-css#18]
In the last exercise, we should instruct the student to add a link to profile.html, from index.html

**Comment by getaaron** [comment]
@mikesjewett @stanidesis Which choice do you like better:

1. At the end of `007-profile-page.md` tell them the exact code with the caveat that they'll learn what the `<a>` tag does later
2. Move `010-links.md` before `007-profile-page.md`

I like the second option a little better but I'm not sure if it will interfere with any students currently going through the program (who might need a refresh or something)

**Comment by mikesjewett** [comment]
Yeah, let's go with 1.
