### ISSUE TITLE
Add a test for each paragraph in the Headers exercise

### ISSUE THREAD

**Issue by mikesjewett** [Bloc/workshop-html-css#28]
A student couldn't figure out what was wrong with their code in their solutions for the Headers exercise. Part of the problem was that the tests are not comprehensive. Their code  was missing a period in the `<h1>` and the first paragraph which should've been `<p>English: Hello World</p>`:

![image](https://cloud.githubusercontent.com/assets/1168076/17136524/e9d856f8-5303-11e6-93fc-00226146859d.png)

The test result reports the period error, but doesn't state that there's an expected `<p>English: Hello World</p>`. Can we add a test to cover each paragraph?

**Comment by getaaron** [comment]
There is no expected `<p>English: Hello World</p>` on this exercise. This exercise only has two tests:

```ruby
  it "has an h1 tag" do
    expect(index).to have_tag('h1')
  end
  
  it "has 'Hello World Translations' within an h1 tag" do
    expect(index).to have_tag('h1', text: 'Hello World Translations')
  end
```

All the student needs to pass this exercise is correct `<h1>` text

**Comment by mikesjewett** [comment]
Weird, I could've sworn I tested that. I double-checked and you are correct. Sorry about the false alarm.
